# Generated by Django 2.0.4 on 2018-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('tag', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
